# -*- coding: utf-8 -*-
"""Proyecto Estructuras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15f2x6EUZCK07EN9cfoV6VZpNR7fTwbiu
"""

"""
Proyecto: Sistema de entregas inteligentes por barrios (Bucaramanga)

Descripción:
Este sistema utiliza un árbol binario de búsqueda (BST) para organizar
barrios según su distancia al centro de distribución. Cada barrio contiene
una cola de prioridad (heap) que gestiona los pedidos según su urgencia.

Incluye:
- Inserción de barrios (BST)
- Gestión de pedidos (heap)
- Menú interactivo para el usuario
"""

import heapq

# MODELO DE DATOS

class Pedido:
    """
    Representa un pedido.

    - id: identificador único
    - prioridad: menor número = más urgente
    """
    def __init__(self, id, prioridad):
        self.id = id
        self.prioridad = prioridad

    def __lt__(self, otro):
        return self.prioridad < otro.prioridad


class NodoBarrio:
    """
    Nodo del árbol (representa un barrio)
    """
    def __init__(self, nombre, distancia):
        self.nombre = nombre
        self.distancia = distancia
        self.izq = None
        self.der = None
        self.pedidos = []  # heap

# ÁRBOL BINARIO DE BÚSQUEDA

class ArbolBarrios:

    def __init__(self):
        self.raiz = None

    def insertar(self, nombre, distancia):
        if self.raiz is None:
            self.raiz = NodoBarrio(nombre, distancia)
        else:
            self._insertar(self.raiz, nombre, distancia)

    def _insertar(self, nodo, nombre, distancia):
        if distancia < nodo.distancia:
            if nodo.izq is None:
                nodo.izq = NodoBarrio(nombre, distancia)
            else:
                self._insertar(nodo.izq, nombre, distancia)
        else:
            if nodo.der is None:
                nodo.der = NodoBarrio(nombre, distancia)
            else:
                self._insertar(nodo.der, nombre, distancia)

    def buscar(self, nodo, nombre):
        if nodo is None:
            return None

        if nodo.nombre == nombre:
            return nodo

        encontrado = self.buscar(nodo.izq, nombre)
        if encontrado:
            return encontrado

        return self.buscar(nodo.der, nombre)

    def agregar_pedido(self, barrio, pedido):
        nodo = self.buscar(self.raiz, barrio)
        if nodo:
            heapq.heappush(nodo.pedidos, pedido)
        else:
            raise ValueError(f"Barrio '{barrio}' no encontrado")

    def obtener_siguiente_pedido(self):
        resultado = self._obtener_siguiente(self.raiz)
        return resultado if resultado else "No hay pedidos pendientes"

    def _obtener_siguiente(self, nodo):
        if nodo is None:
            return None

        # 1. barrios más cercanos
        pedido = self._obtener_siguiente(nodo.izq)
        if pedido:
            return pedido

        # 2. barrio actual
        if nodo.pedidos:
            siguiente = heapq.heappop(nodo.pedidos)
            return (
                f"Pedido {siguiente.id} → Barrio: {nodo.nombre} "
                f"(Distancia: {nodo.distancia} km, Prioridad: {siguiente.prioridad})"
            )

        # 3. barrios más lejanos
        return self._obtener_siguiente(nodo.der)

# MENÚ INTERACTIVO

def main():
    arbol = ArbolBarrios()

    # Barrios base
    arbol.insertar("Centro", 2)
    arbol.insertar("Cabecera", 5)
    arbol.insertar("San Alonso", 1)
    arbol.insertar("Floridablanca", 8)
    arbol.insertar("Girón", 10)

    while True:
        print("\n===== SISTEMA DE ENTREGAS =====")
        print("1. Agregar pedido")
        print("2. Ver siguiente pedido a entregar")
        print("3. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            barrio = input("Ingrese el barrio: ")
            id_pedido = int(input("ID del pedido: "))
            prioridad = int(input("Prioridad (1 = urgente): "))

            try:
                arbol.agregar_pedido(barrio, Pedido(id_pedido, prioridad))
                print("Pedido agregado correctamente ")
            except ValueError as e:
                print(e)

        elif opcion == "2":
            print("\nSiguiente pedido:")
            print(arbol.obtener_siguiente_pedido())

        elif opcion == "3":
            print("Saliendo del sistema...")
            break

        else:
            print("Opción inválida")


if __name__ == "__main__":
    main()