# -*- coding: utf-8 -*-
"""Tercer_avance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkWUsmwnkheDyKICedbnxPy0XMn8Nnz1
"""

"""
PROYECTO:
Sistema Inteligente de Gestión de Entregas
Implementación de Grafos con Dijkstra
"""

import heapq

class GrafoEntregas:

    def __init__(self):
        # Diccionario que almacena el grafo
        self.grafo = {}


    # AGREGAR BARRIO
    def agregar_barrio(self, barrio):
        if barrio not in self.grafo:
            self.grafo[barrio] = {}
            print(f"\nBarrio '{barrio}' agregado correctamente.")
            return True
        else:
            print("\nEl barrio ya existe.")
            return False

    # AGREGAR RUTA
    def agregar_ruta(self, origen, destino, distancia):
        # Si alguno de los barrios no existe, lo creamos automáticamente
        if origen not in self.grafo:
            self.grafo[origen] = {}
            print(f"-> Barrio '{origen}' no existía. Creado automáticamente.")

        if destino not in self.grafo:
            self.grafo[destino] = {}
            print(f"-> Barrio '{destino}' no existía. Creado automáticamente.")

        # Grafo no dirigido
        self.grafo[origen][destino] = distancia
        self.grafo[destino][origen] = distancia

        print(f"\nRuta agregada entre {origen} y {destino} ({distancia} km).")

    # ELIMINAR BARRIO
    def eliminar_barrio(self, barrio):
        if barrio in self.grafo:
            # Elimina conexiones del barrio
            for vecino in list(self.grafo[barrio].keys()):
                del self.grafo[vecino][barrio]

            # Elimina el barrio
            del self.grafo[barrio]
            print(f"\nBarrio '{barrio}' eliminado.")
        else:
            print("\nEl barrio no existe.")

    # ELIMINAR RUTA
    def eliminar_ruta(self, origen, destino):
        if origen in self.grafo and destino in self.grafo[origen]:
            del self.grafo[origen][destino]
            del self.grafo[destino][origen]
            print("\nRuta eliminada correctamente.")
        else:
            print("\nLa ruta no existe.")

    # BUSCAR BARRIO
    def buscar_barrio(self, barrio):
        if barrio in self.grafo:
            print(f"\nEl barrio '{barrio}' sí existe.")
            print("Conexiones:")
            if self.grafo[barrio]:
                for vecino, distancia in self.grafo[barrio].items():
                    print(f" - {vecino}: {distancia} km")
            else:
                print("Este barrio no tiene conexiones.")
        else:
            print("\nEl barrio no existe.")

    # MOSTRAR GRAFO
    def mostrar_grafo(self):
        print("\n===== GRAFO DE ENTREGAS =====")
        if not self.grafo:
            print("El grafo está vacío.")
            return

        for barrio in self.grafo:
            print(f"\n{barrio}")
            if self.grafo[barrio]:
                for vecino, distancia in self.grafo[barrio].items():
                    print(f"  -> {vecino}: {distancia} km")
            else:
                print("  Sin conexiones")


    # DIJKSTRA - RUTA MÁS CORTA
    def ruta_mas_corta(self, inicio, fin):
        if inicio not in self.grafo or fin not in self.grafo:
            print("\nUno de los barrios no existe en el sistema.")
            return

        # Cola de prioridad
        cola = [(0, inicio)]

        # Distancias mínimas
        distancias = {barrio: float('inf') for barrio in self.grafo}
        distancias[inicio] = 0

        # Para guardar caminos
        anteriores = {barrio: None for barrio in self.grafo}

        while cola:
            distancia_actual, actual = heapq.heappop(cola)

            # Si encontramos una distancia mayor en la cola, la ignoramos
            if distancia_actual > distancias[actual]:
                continue

            for vecino, peso in self.grafo[actual].items():
                nueva_distancia = distancia_actual + peso

                if nueva_distancia < distancias[vecino]:
                    distancias[vecino] = nueva_distancia
                    anteriores[vecino] = actual
                    heapq.heappush(cola, (nueva_distancia, vecino))

        # Si no existe ruta
        if distancias[fin] == float('inf'):
            print(f"\nNo existe una ruta transitable entre '{inicio}' y '{fin}'.")
            return

        # Reconstrucción del camino
        camino = []
        actual = fin
        while actual is not None:
            camino.append(actual)
            actual = anteriores[actual]
        camino.reverse()

        # Mostrar resultados
        print("\n===== RUTA MÁS CORTA =====")
        print(" -> ".join(camino))
        print(f"Distancia total: {distancias[fin]} km")


# MENÚ PRINCIPAL
def main():
    sistema = GrafoEntregas()

    # Datos iniciales de prueba
    sistema.agregar_barrio("Centro")
    sistema.agregar_barrio("Cabecera")
    sistema.agregar_barrio("San Alonso")

    sistema.agregar_ruta("Centro", "Cabecera", 2)
    sistema.agregar_ruta("Centro", "San Alonso", 1)

    while True:
        print("\n========== MENÚ ==========")
        print("1. Agregar barrio")
        print("2. Agregar ruta")
        print("3. Eliminar barrio")
        print("4. Eliminar ruta")
        print("5. Buscar barrio")
        print("6. Mostrar grafo")
        print("7. Ruta más corta")
        print("8. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            barrio = input("Nombre del nuevo barrio: ").strip()
            if barrio == "":
                print("El nombre no puede estar vacío.")
                continue

            # Se agrega el barrio
            sistema.agregar_barrio(barrio)

            conectar = input("¿Desea agregar una conexión inmediata? (s/n): ").lower().strip()
            if conectar == "s":
                vecino = input("¿Con qué barrio lo desea conectar?: ").strip()
                try:
                    distancia = int(input("Distancia en km: "))
                    if distancia < 0:
                        print("La distancia no puede ser negativa.")
                        continue
                    # Llama al método optimizado
                    sistema.agregar_ruta(barrio, vecino, distancia)
                except ValueError:
                    print("\nError: La distancia debe ser un número entero.")

        elif opcion == "2":
            origen = input("Barrio origen: ").strip()
            destino = input("Barrio destino: ").strip()
            try:
                distancia = int(input("Distancia en km: "))
                if distancia < 0:
                    print("La distancia no puede ser negativa.")
                    continue
                sistema.agregar_ruta(origen, destino, distancia)
            except ValueError:
                print("\nError: La distancia debe ser un número entero.")

        elif opcion == "3":
            barrio = input("Barrio a eliminar: ").strip()
            sistema.eliminar_barrio(barrio)

        elif opcion == "4":
            origen = input("Barrio origen: ").strip()
            destino = input("Barrio destino: ").strip()
            sistema.eliminar_ruta(origen, destino)

        elif opcion == "5":
            barrio = input("Barrio a buscar: ").strip()
            sistema.buscar_barrio(barrio)

        elif opcion == "6":
            sistema.mostrar_grafo()

        elif opcion == "7":
            inicio = input("Barrio de inicio: ").strip()
            fin = input("Barrio destino: ").strip()
            sistema.ruta_mas_corta(inicio, fin)

        elif opcion == "8":
            print("\nSaliendo del sistema logístico...")
            break
        else:
            print("\nOpción inválida.")


if __name__ == "__main__":
    main()